# Read more about GitHub App Manifests:
# https://docs.github.com/en/developers/apps/creating-a-github-app-from-a-manifest

name: Code Copilot
url: https://github.com/apps/code-copilot
description: Prepare your PRs for a smooth landing
public: false

default_events:
- pull_request

default_permissions:
  metadata: read
  pull_requests: write
